dist: trusty
sudo: false

language: php
php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install

before_script:
  # create directory for coverage reports
  - mkdir -p build/logs

script:
  - php vendor/bin/phpcs -q
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  # upload coverage reports to Coveralls
  - travis_retry wget -q https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - travis_retry php php-coveralls.phar
